<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome">Nome do Usuário</span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor">0</span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<form action="/quem_seguir" method="get">
								<div class="input-group mb-3">
									<input name="search" type="text" class="form-control" placeholder="Quem você está procurando?">
									<div class="input-group-append">
										<button class="btn btn-primary" type="submit">Procurar</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

			<?php
				if(isset($this->data->searchResults))
				{
					if(count($this->data->searchResults) > 0)
					{
						$users = $this->data->searchResults;

						foreach($users as $user)
						{		
			?>
			<div class="row mb-2">
				<div class="col">
					<div class="card">
						<div class="card-body">
							<div class="row">
								<div class="col-md-6">
									<?=$user->getName()?>
								</div>
							
								<div class="col-md-6 d-flex justify-content-end">
									<?php if($user->getId() != $_SESSION['id']) { ?>
									<div>
										<a href="/action?action=follow&id=<?= $user->getId() ?>" class="btn btn-success">Seguir</a>
										<a href="/action?action=unfollow&id=<?= $user->getId() ?>" class="btn btn-danger">Deixar de seguir</a>
									</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<?php
						}
					}
					else
					{
			?>
			<p>Nenhum usuário encontrado.</p>
			<?php
					}
				}
			?>
		</div>
	</div>
</div>