<?php

	use App\Connection;
	use App\Models\Tweet;
	use App\Models\User;

	$user = User::getUsersByEmail($_SESSION['email'], Connection::getDb())[0];
?>

<nav class="navbar navbar-expand-lg menu">
	<div class="container">
	  <div class="navbar-nav">
	  	<a class="menuItem" href="/timeline">
	  		Home
	  	</a>

	  	<a class="menuItem" href="/sair">
	  		Sair
	  	</a>
			<img src="/img/twitter_logo.png" class="menuIco" />
	  </div>
	</div>
</nav>

<div class="container mt-5">
	<div class="row pt-2">
		
		<div class="col-md-3">

			<div class="perfil">
				<div class="perfilTopo">

				</div>

				<div class="perfilPainel">
					
					<div class="row mt-2 mb-2">
						<div class="col mb-2">
							<span class="perfilPainelNome"><?=$user->getName()?></span>
						</div>
					</div>

					<div class="row mb-2">

						<div class="col">
							<span class="perfilPainelItem">Tweets</span><br />
							<span class="perfilPainelItemValor"><?=count($user->getTweets())?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguindo</span><br />
							<span class="perfilPainelItemValor"><?= $this->data->userInfo['following'] ?></span>
						</div>

						<div class="col">
							<span class="perfilPainelItem">Seguidores</span><br />
							<span class="perfilPainelItemValor"><?= $this->data->userInfo['followers'] ?></span>
						</div>

					</div>

				</div>
			</div>

		</div>

		<div class="col-md-6">
			<div class="row mb-2">
				<div class="col tweetBox">
					<form id="form-tweet" action="/tweet" method="post">
						<textarea id="text-tweet" name="tweet" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
						
						<div class="col mt-2 d-flex justify-content-end">
							<button id="btn-tweet" type="submit" class="btn btn-primary">Tweet</button>
						</div> 

					</form>
				</div>
			</div>

			<?php foreach($this->data->tweets as $tweet) { ?>
			<div class="row tweet p-1">
				<div class="col">
					<p><strong><?=$tweet['nome']?></strong> <span class="text text-muted"> - <?=$tweet['data']?></span></p>
					<p><?=$tweet['tweet']?></p>

					<?php if($tweet['id_usuario'] == $_SESSION['id']) {?>
					<br />
					<form action="/remover_tweet?id=<?= $tweet['id'] ?>" method="post">
						<div class="col d-flex justify-content-end">
							<button type="submit" class="btn btn-danger"><small>Remover</small></button>
						</div>
					</form>
					<?php } ?>
				</div>
			</div>
			<?php } ?>

			<div class="row mt-3">
				<nav aria-label="Page navigation example">
					<ul class="pagination">
						<?php for($i = 1; $i <= $this->data->totalPages; $i++) { ?>
							<li class="page-item <?php if($i == $this->page) { ?>active<?php } ?>">
								<a class="page-link" href="?pagina=<?=$i?>"><?=$i?></a>
							</li>
						<?php } ?>
					</ul>
				</nav>
			</div>

		</div>


		<div class="col-md-3">
			<div class="quemSeguir">
				<span class="quemSeguirTitulo">Quem seguir</span><br />
				<hr />
				<a href="/quem_seguir" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
			</div>
		</div>

	</div>
</div>